version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8085"
    volumes:
      - ./:/app
    restart: unless-stopped
