"""initial_migration

Revision ID: 24beaefefc85
Revises: 
Create Date: 2025-05-16 23:40:06.914745+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '24beaefefc85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oil_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('PETROL', 'DIESEL', 'GAS', name='oiltype'), nullable=False),
    sa.Column('oil_document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('userId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oil_resources_date'), 'oil_resources', ['date'], unique=False)
    op.create_index(op.f('ix_oil_resources_email'), 'oil_resources', ['email'], unique=False)
    op.create_index(op.f('ix_oil_resources_userId'), 'oil_resources', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oil_resources_userId'), table_name='oil_resources')
    op.drop_index(op.f('ix_oil_resources_email'), table_name='oil_resources')
    op.drop_index(op.f('ix_oil_resources_date'), table_name='oil_resources')
    op.drop_table('oil_resources')
    # ### end Alembic commands ###
